---

- name: GNOME Desktop - Set 24h time layout
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
  when: gnome_topbar_time_24h
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Set 24h time layout | CLI
  command: dconf write /org/gnome/desktop/interface/clock-format 24
  when: (gnome_topbar_time_24h) and (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable seconds
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "{{ gnome_topbar_time_seconds | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable seconds | CLI
  command: dbus-launch dconf write /org/gnome/desktop/interface/clock-show-seconds "{{ gnome_topbar_time_seconds | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Show/hide weekday
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "{{ gnome_topbar_show_weekday  | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Show/hide weekday | CLI
  command: dbus-launch dconf write /org/gnome/desktop/interface/clock-show-weekday "{{ gnome_topbar_show_weekday  | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Show/hide battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "{{ gnome_battery_percentage | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Show/hide battery percentage | CLI
  command: dbus-launch dconf write /org/gnome/desktop/interface/show-battery-percentage "{{ gnome_battery_percentage | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable animiations
  dconf:
    key: "/org/gnome/desktop/interface/enable-animations"
    value: "{{ gnome_shell_animations | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable animiations | CLI
  command: dbus-launch dconf write /org/gnome/desktop/interface/enable-animations "{{ gnome_shell_animations | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable hot-corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "{{ gnome_shell_hotcorners | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable hot-corners | CLI
  command: dbus-launch dconf write /org/gnome/desktop/interface/enable-hot-corners "{{ gnome_shell_hotcorners | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable minimize/maximize buttons
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "{{ gnome_wm_buttons | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable minimize/maximize buttons | CLI
  command: dbus-launch dconf write /org/gnome/desktop/wm/preferences/button-layout "{{ gnome_wm_buttons | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable ambient light sensor
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
    value: "{{ gnome_ambient_light | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable ambient light sensor | CLI
  command: dbus-launch dconf write /org/gnome/settings-daemon/plugins/power/ambient-enabled "{{ gnome_ambient_light | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable natural scrolling (on notebook)
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "{{ gnome_mouse_natural_scrolling | lower }}"
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable natural scrolling (on notebook)
  command: dbus-launch dconf write /org/gnome/desktop/peripherals/touchpad/natural-scroll "{{ gnome_mouse_natural_scrolling | lower }}"
  when: (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Enable/Disable showing desktop shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/show-desktop"
    value: "['<Super>d']"
  when: gnome_desktop_shortcut
  register: result
  failed_when: result.rc|d(0) not in [ 0, 1 ]

- name: GNOME Desktop - Enable/Disable showing desktop shortcut | CLI
  command: dbus-launch dconf write /org/gnome/desktop/wm/keybindings/show-desktop "['<Super>d']"
  when: gnome_desktop_shortcut and (result.rc|d(0) in [ 1 ])

############################################################################################################

- name: GNOME Desktop - Additional settings
#  dconf:
#    key: "{{ item.setting }}"
#    value: "{{ item.value | default(omit) }}"
#    state: "{{ item.state | default('present') }}"
  include_tasks: dconf.yml
  loop: "{{ gnome_additional_settings }}"
  when: gnome_additional_settings is defined

############################################################################################################

- debug: var=ansible_user_id

- name: Create extension directory
  file:
    path: ~/.local/share/gnome-shell/extensions
    owner: "{{ ansible_user_id }}"
    mode: '0750'
    state: directory
  when: gnome_extensions is defined

- name: Install extensions
  block:
    - name: Download archive
      get_url:
        url: "{{ item.url }}"
        dest: ~/.local/share/gnome-shell/extensions/
      loop: "{{ gnome_extensions }}"

    - name: Create directory
      file:
        path: "~/.local/share/gnome-shell/extensions/{{ item.name }}"
        owner: "{{ ansible_user_id }}"
        mode: '0750'
        state: directory
      loop: "{{ gnome_extensions }}"

    - name: Extract archive
      unarchive:
        src: "~/.local/share/gnome-shell/extensions/{{ item.url | basename }}"
        dest: "~/.local/share/gnome-shell/extensions/{{ item.name }}"
        remote_src: yes
      loop: "{{ gnome_extensions }}"

    - name: id
      command: id
      register: result
    - debug: var=result

    - name: enable
####      shell: dbus-launch gnome-extensions enable {{ item.name }}
      command: dbus-launch gnome-extensions enable {{ item.name }}
####      command: |
####           dbus-launch gdbus call --session \
####           --dest org.gnome.Shell.Extensions \
####           --object-path /org/gnome/Shell/Extensions \
####           --method org.gnome.Shell.Extensions.InstallRemoteExtension \
####           {{ item.name }}
      loop: "{{ gnome_extensions }}"
      register: result
    - debug: var=result
####    - pause:

  when: gnome_extensions is defined
