---
- name: GNOME Desktop - Set 24h time layout
  dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
  when: gnome_topbar_time_24h

- name: GNOME Desktop - Enable/Disable seconds
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-seconds"
    value: "{{ gnome_topbar_time_seconds | lower }}"

- name: GNOME Desktop - Show/hide weekday
  dconf:
    key: "/org/gnome/desktop/interface/clock-show-weekday"
    value: "{{ gnome_topbar_show_weekday  | lower }}"

- name: GNOME Desktop - Show/hide battery percentage
  dconf:
    key: "/org/gnome/desktop/interface/show-battery-percentage"
    value: "{{ gnome_battery_percentage | lower }}"

- name: GNOME Desktop - Enable/Disable animiations
  dconf:
    key: "/org/gnome/desktop/interface/enable-animations"
    value: "{{ gnome_shell_animations | lower }}"

- name: GNOME Desktop - Enable/Disable hot-corners
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: "{{ gnome_shell_hotcorners | lower }}"

- name: GNOME Desktop - Enable/Disable minimize/maximize buttons
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "{{ gnome_wm_buttons | lower }}"

- name: GNOME Desktop - Enable/Disable ambient light sensor
  dconf:
    key: "/org/gnome/settings-daemon/plugins/power/ambient-enabled"
    value: "{{ gnome_ambient_light | lower }}"

- name: GNOME Desktop - Enable/Disable natural scrolling (on notebook)
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "{{ gnome_mouse_natural_scrolling | lower }}"

- name: GNOME Desktop - Enable/Disable showing desktop shortcut
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/show-desktop"
    value: "['<Super>d']"
  when: gnome_desktop_shortcut

- name: GNOME Desktop - Additional settings
  dconf:
    key: "{{ item.setting }}"
    value: "{{ item.value | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ gnome_additional_settings }}"
  when: gnome_additional_settings is defined

- name: Create extension directory
  file:
    path: ~/.local/share/gnome-shell/extensions
    owner: "{{ ansible_user_id }}"
    mode: '0750'
    state: directory
  when: gnome_extensions is defined

- name: Install extensions
  block:
    - name: Download archive
      get_url:
        url: "{{ item.url }}"
        dest: ~/.local/share/gnome-shell/extensions/
      loop: "{{ gnome_extensions }}"

    - name: Create directory
      file:
        path: "~/.local/share/gnome-shell/extensions/{{ item.name }}"
        owner: "{{ ansible_user_id }}"
        mode: '0750'
        state: directory
      loop: "{{ gnome_extensions }}"

    - name: Extract archive
      unarchive:
        src: "~/.local/share/gnome-shell/extensions/{{ item.url | basename }}"
        dest: "~/.local/share/gnome-shell/extensions/{{ item.name }}"
      loop: "{{ gnome_extensions }}"
  when: gnome_extensions is defined
