---
- name: Converge
  hosts: all
  become: false
  tasks:
    - name: "Include gnome-desktop"
      include_role:
        name: "gnome-desktop"
      vars:
        gnome_additional_settings:
          - setting: "/org/gnome/desktop/privacy/report-technical-problems"
            value: "false"
          - setting: "/org/gnome/desktop/privacy/send-software-usage-stats"
            value: "false"
