---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: ubuntu-focal
    box: generic/ubuntu2004
    provider: virtualbox
    memory: 1024
  - name: almalinux-8
    box: almalinux/8
    provider: virtualbox
    memory: 1024
  - name: fedora-35
    box: fedora/35-cloud-base
    provider: virtualbox
    memory: 1024
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
